// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: match/proto/match.proto

package matchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUser      int64                  `protobuf:"varint,1,opt,name=from_user,json=fromUser,proto3" json:"from_user,omitempty"`
	ToUser        int64                  `protobuf:"varint,2,opt,name=to_user,json=toUser,proto3" json:"to_user,omitempty"`
	IsLike        bool                   `protobuf:"varint,3,opt,name=is_like,json=isLike,proto3" json:"is_like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_match_proto_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_match_proto_match_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetFromUser() int64 {
	if x != nil {
		return x.FromUser
	}
	return 0
}

func (x *LikeRequest) GetToUser() int64 {
	if x != nil {
		return x.ToUser
	}
	return 0
}

func (x *LikeRequest) GetIsLike() bool {
	if x != nil {
		return x.IsLike
	}
	return false
}

type CheckMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1         int64                  `protobuf:"varint,1,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         int64                  `protobuf:"varint,2,opt,name=user2,proto3" json:"user2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMatchRequest) Reset() {
	*x = CheckMatchRequest{}
	mi := &file_match_proto_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMatchRequest) ProtoMessage() {}

func (x *CheckMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMatchRequest.ProtoReflect.Descriptor instead.
func (*CheckMatchRequest) Descriptor() ([]byte, []int) {
	return file_match_proto_match_proto_rawDescGZIP(), []int{1}
}

func (x *CheckMatchRequest) GetUser1() int64 {
	if x != nil {
		return x.User1
	}
	return 0
}

func (x *CheckMatchRequest) GetUser2() int64 {
	if x != nil {
		return x.User2
	}
	return 0
}

type GetCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidatesRequest) Reset() {
	*x = GetCandidatesRequest{}
	mi := &file_match_proto_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidatesRequest) ProtoMessage() {}

func (x *GetCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidatesRequest.ProtoReflect.Descriptor instead.
func (*GetCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_match_proto_match_proto_rawDescGZIP(), []int{2}
}

func (x *GetCandidatesRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

type LikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	mi := &file_match_proto_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_match_proto_match_proto_rawDescGZIP(), []int{3}
}

func (x *LikeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         bool                   `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMatchResponse) Reset() {
	*x = CheckMatchResponse{}
	mi := &file_match_proto_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMatchResponse) ProtoMessage() {}

func (x *CheckMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMatchResponse.ProtoReflect.Descriptor instead.
func (*CheckMatchResponse) Descriptor() ([]byte, []int) {
	return file_match_proto_match_proto_rawDescGZIP(), []int{4}
}

func (x *CheckMatchResponse) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

type GetCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*User                `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidatesResponse) Reset() {
	*x = GetCandidatesResponse{}
	mi := &file_match_proto_match_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidatesResponse) ProtoMessage() {}

func (x *GetCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_match_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidatesResponse.ProtoReflect.Descriptor instead.
func (*GetCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_match_proto_match_proto_rawDescGZIP(), []int{5}
}

func (x *GetCandidatesResponse) GetCandidates() []*User {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TelegramId    int64                  `protobuf:"varint,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,8,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	IsVisible     bool                   `protobuf:"varint,9,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_match_proto_match_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_match_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_match_proto_match_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *User) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *User) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_match_proto_match_proto protoreflect.FileDescriptor

const file_match_proto_match_proto_rawDesc = "" +
	"\n" +
	"\x17match/proto/match.proto\x12\x05match\"\\\n" +
	"\vLikeRequest\x12\x1b\n" +
	"\tfrom_user\x18\x01 \x01(\x03R\bfromUser\x12\x17\n" +
	"\ato_user\x18\x02 \x01(\x03R\x06toUser\x12\x17\n" +
	"\ais_like\x18\x03 \x01(\bR\x06isLike\"?\n" +
	"\x11CheckMatchRequest\x12\x14\n" +
	"\x05user1\x18\x01 \x01(\x03R\x05user1\x12\x14\n" +
	"\x05user2\x18\x02 \x01(\x03R\x05user2\"7\n" +
	"\x14GetCandidatesRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\"(\n" +
	"\fLikeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x12CheckMatchResponse\x12\x14\n" +
	"\x05match\x18\x01 \x01(\bR\x05match\"D\n" +
	"\x15GetCandidatesResponse\x12+\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\v.match.UserR\n" +
	"candidates\"\x96\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\x03R\n" +
	"telegramId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tphoto_url\x18\b \x01(\tR\bphotoUrl\x12\x1d\n" +
	"\n" +
	"is_visible\x18\t \x01(\bR\tisVisible\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt2\xce\x01\n" +
	"\fMatchService\x12/\n" +
	"\x04Like\x12\x12.match.LikeRequest\x1a\x13.match.LikeResponse\x12A\n" +
	"\n" +
	"CheckMatch\x12\x18.match.CheckMatchRequest\x1a\x19.match.CheckMatchResponse\x12J\n" +
	"\rGetCandidates\x12\x1b.match.GetCandidatesRequest\x1a\x1c.match.GetCandidatesResponseB\x15Z\x13match/proto;matchpbb\x06proto3"

var (
	file_match_proto_match_proto_rawDescOnce sync.Once
	file_match_proto_match_proto_rawDescData []byte
)

func file_match_proto_match_proto_rawDescGZIP() []byte {
	file_match_proto_match_proto_rawDescOnce.Do(func() {
		file_match_proto_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_match_proto_match_proto_rawDesc), len(file_match_proto_match_proto_rawDesc)))
	})
	return file_match_proto_match_proto_rawDescData
}

var file_match_proto_match_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_match_proto_match_proto_goTypes = []any{
	(*LikeRequest)(nil),           // 0: match.LikeRequest
	(*CheckMatchRequest)(nil),     // 1: match.CheckMatchRequest
	(*GetCandidatesRequest)(nil),  // 2: match.GetCandidatesRequest
	(*LikeResponse)(nil),          // 3: match.LikeResponse
	(*CheckMatchResponse)(nil),    // 4: match.CheckMatchResponse
	(*GetCandidatesResponse)(nil), // 5: match.GetCandidatesResponse
	(*User)(nil),                  // 6: match.User
}
var file_match_proto_match_proto_depIdxs = []int32{
	6, // 0: match.GetCandidatesResponse.candidates:type_name -> match.User
	0, // 1: match.MatchService.Like:input_type -> match.LikeRequest
	1, // 2: match.MatchService.CheckMatch:input_type -> match.CheckMatchRequest
	2, // 3: match.MatchService.GetCandidates:input_type -> match.GetCandidatesRequest
	3, // 4: match.MatchService.Like:output_type -> match.LikeResponse
	4, // 5: match.MatchService.CheckMatch:output_type -> match.CheckMatchResponse
	5, // 6: match.MatchService.GetCandidates:output_type -> match.GetCandidatesResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_match_proto_match_proto_init() }
func file_match_proto_match_proto_init() {
	if File_match_proto_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_proto_match_proto_rawDesc), len(file_match_proto_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_match_proto_match_proto_goTypes,
		DependencyIndexes: file_match_proto_match_proto_depIdxs,
		MessageInfos:      file_match_proto_match_proto_msgTypes,
	}.Build()
	File_match_proto_match_proto = out.File
	file_match_proto_match_proto_goTypes = nil
	file_match_proto_match_proto_depIdxs = nil
}
